### ISSUE TITLE
Label file doesn't contain the correct classes

### ISSUE THREAD

**Issue by DarylWM** [prabindh/euclid#1]
I labelled several objects as class 1, another object as class 2, and another as class 3. However, the saved label file labelled the first object as class 0, and all the others as class 1.

![image](https://cloud.githubusercontent.com/assets/1016303/21171008/41f72af2-c21d-11e6-9c7a-2d25786e6b42.png)

And the entries in the label file:
0 0.8408724 0.5775401 0.0775444 0.4866310
1 0.7257674 0.6898396 0.0686591 0.5935829
1 0.4204362 0.5561497 0.0201939 0.2192513
1 0.3994346 0.5561497 0.0218094 0.2299465
1 0.4697092 0.5307487 0.0185784 0.1844920
1 0.6466074 0.7286096 0.0751212 0.2967914
1 0.6021809 0.3850267 0.0395800 0.7005348

**Comment by prabindh** [comment]
Will get back with an update shortly.

**Comment by prabindh** [comment]
I just checked, and it does not behave like what you are seeing. It is saving the correct class IDs (0 based index). Please use "git pull origin master" to get the latest version. Also, in the latest version, I have added a line in Line# 373 (commented out, you can uncomment), that will show (via Alert popup) the Class Label that is getting saved each time.

**Comment by DarylWM** [comment]
It's all good - I didn't get that I needed to change to 'KITTI' mode on line 116.

Thanks for writing this utility. It's just what I needed to create a new DetectNet data set.

**Comment by prabindh** [comment]
There was a critical bug fixed in parsing of already existing labels in last update. In addition, an enhancement to be able to use the Keyboard "x" to draw bounding box instead of mouse click, has been added for faster processing of databases. Please check latest commit (1/18/2017).
