### ISSUE TITLE
dots in image file names

### ISSUE THREAD

**Issue by dpogosov** [prabindh/euclid#10]
to detect a file extension euclid searches the dot from left to right (from begin to end), so if the file has dots in names then txt file with labels has different name.
Example:
for 'cat.in_house.jpg', euclid will create 'cat.txt' because all after the first dot is lost
Solution: change the direction of search of the dot from right to left (from end of the name).

**Comment by prabindh** [comment]
Could you pls check master if 87db3a2783293eb81418a85edd69c5299780a8ec fixes ?
