### ISSUE TITLE
Even after changing the LabelMode to KITTI, I'm getting the annotations in YOLO format

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [prabindh/euclid#2]
![image](https://cloud.githubusercontent.com/assets/22409116/21798068/88b12ff8-d738-11e6-8161-92367c5ea106.png)

0 0.6008333 0.5930556 0.1316667 0.2305556
1 0.4375000 0.5472222 0.0316667 0.1611111
2 0.2791667 0.5402778 0.0450000 0.1805556

**Comment by SumanthReddyKaliki** [comment]
Also, it will be helpful, if can comment on my doubt. Before starting labelling my dataset, should I resize all my images into any standard size. What is the input image size for yolo .

**Comment by prabindh** [comment]
If you had created an earlier label file with Yolo format it sticks to that.  Could you delete the created label folder,  change the label format,  then try again while I fix in code?  Thx

**Comment by prabindh** [comment]
On size of images,  it really depends on your HW system for training, and detection. Needs lot of experimentation

**Comment by SumanthReddyKaliki** [comment]
I have found it, initially i had one image with yolo format. I understand that, but should i maintain all images with same size like 256x256 or 416x416 something like that. What does yolo expect.

**Comment by prabindh** [comment]
Since ease of use is important, the behaviour is such that, if you are continuing on an already existing session with labelled data, you should not need to change the type again. Hence I am planning to retain it as is. Can I close the original issue then ?

**Comment by prabindh** [comment]
Selection boxes for kitti/yolo format, are now added in the latest checkin. Please validate and close the issue if there is no further action needed on this.

**Comment by SumanthReddyKaliki** [comment]
Thanks
