### ISSUE TITLE
a bug with reading images

### ISSUE THREAD

**Issue by VanitarNordic** [prabindh/euclid#3]
Hello,

When I assign a folder which contains images to the program, it reads the quantity of images one time more, for example if there are 20 images in the folder, the program shows 40. and when I pass from 20th image and the software shows 21 of course, it actually starts from the first image!

Why?!

**Comment by prabindh** [comment]
I am unable to replicate this behaviour. Could you please indicate the list of files (with filename and extension) in your folder structure ? Thx

**Comment by VanitarNordic** [comment]
Yes,

file names are in this format: `000.png`, `001.png`, `002.png` and so on.

**Comment by prabindh** [comment]
I tried with this combination and still unable to reproduce. I test on Linux. Are you trying on Windows or Mac ? Please let me know so I can try out.

**Comment by VanitarNordic** [comment]
Yes, I am using windows, specifically windows 10.

**Comment by prabindh** [comment]
Please check with latest commit, I have checked on Windows, able to replicate it, and fixed it.

**Comment by VanitarNordic** [comment]
Thank you for your attention. Big like.

**Comment by prabindh** [comment]
There was a critical bug fixed in parsing of already existing labels in last update. In addition, an enhancement to be able to use the Keyboard "x" to draw bounding box instead of mouse click, has been added for faster processing of databases. Please check latest commit (1/18/2017).

**Comment by VanitarNordic** [comment]
Fantastic, nice work.
