### ISSUE TITLE
Yolo format is not working properly

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [prabindh/euclid#4]
Hi,
DetectNet format is working very well. But YOLO format is not working properly. Before saving the labels it will show correctly all the ClassLabels correctly which are selected. But after saving the labels, it saves them completely different. As an example check the below figures. Left (before saving) and right (after saving). 
![image](https://cloud.githubusercontent.com/assets/22409116/22053568/8ae80946-dd77-11e6-9361-fb66b1adaf14.png)
![image](https://cloud.githubusercontent.com/assets/22409116/22053584/9ffd02d2-dd77-11e6-8cfc-114eec0e5d36.png)

Also in my original dataset, most of the images have a single object in that. Suppose in my first image i have a object of class 3 and second image has class 4, even after changing the class label it is saving the second image as class 4.
![image](https://cloud.githubusercontent.com/assets/22409116/22053697/90006c10-dd78-11e6-8615-cc8a8046b3a5.png)

![image](https://cloud.githubusercontent.com/assets/22409116/22053717/aafd4966-dd78-11e6-9b51-24895ace9bf5.png)

![image](https://cloud.githubusercontent.com/assets/22409116/22053758/c9837b3a-dd78-11e6-8faa-44ecfb509a96.png)
![image](https://cloud.githubusercontent.com/assets/22409116/22053776/e9395008-dd78-11e6-90b6-901907bd5c5b.png)

In the above image 1( Before saving for class 3)
                     image 2 (After saving for class 3)
                     image 3 (Before saving for class 4)
                     image 4 (After saving for class 4)

I tried this on windows 10 and ubantu 16.04. But I got the same issue on both.

**Comment by SumanthReddyKaliki** [comment]
Please check this, I need to annotate my dataset as soon as possible in yolo format. Even tough I select one class label, it is saving some other class label

**Comment by prabindh** [comment]
Can you check the latest checkin ? It fixes the label issue when moving across files. Also, please note, the selection of class remains across files, and does not reset to 0 for a new file.

**Comment by SumanthReddyKaliki** [comment]
I am using the latest commit, that you updated 2 days back. Please check with some images using Yolo format

**Comment by prabindh** [comment]
Does the git log show latest commit as "Clearing labels when moving across files - with ID 579d88c318a8786c89561ed24aca4d83033badbf"

**Comment by SumanthReddyKaliki** [comment]
I have tried with the latest commit, that you have done half an hour back. I all working fine. Thank you very much for the help. What was the problem with the initial commit. i'm asking this out of curiosity. If possible please answer this question. Any way I'm going to close the issue. Thanks once again
