### ISSUE TITLE
Image dimensions error ...

### ISSUE THREAD

**Issue by VanitarNordic** [prabindh/euclid#5]
Hello,

I see this error with some images, why you put this term on input images? 

![2017-02-07_23-47-35](https://cloud.githubusercontent.com/assets/18719591/22709830/78781430-ed90-11e6-8639-d7f93e749b64.png)

**Comment by prabindh** [comment]
The training phase usually involves a resize step. But it is better to resize to the typical dimensions of the framework that is being used. Typical sizes are 256x256, etc. Anything larger than a typical size is flagged with an error message as you noted above. To avoid, please resize to a smaller size.

**Comment by VanitarNordic** [comment]
Alright, could you add a bonus tool inside your code to do this resizing (by keeping the aspect ration of course)?

besides I have these suggestions: 

- add description about shortcuts in the github readme or in the program form.
- replace class names from button to radio button

**Comment by ip1981** [comment]
The tool exists http://www.imagemagick.org/Usage/resize/

**Comment by prabindh** [comment]
If we resize inside the tool, what if the user needs to control if (a) Replace the original file or (b) Create a copy and resize a new file ?

**Comment by VanitarNordic** [comment]
That's correct.
