### ISSUE TITLE
different python versions (imports)

### ISSUE THREAD

**Issue by dpogosov** [prabindh/euclid#7]
Hi, it does not work with python 3.5.2, but if we change just 3 lines of the imports we can switch it to python 3.

# these 3 lines for python 3
from tkinter import *
from tkinter import messagebox as tkMessageBox
from tkinter import filedialog as tkFileDialog

# these 3 lines for python 2
from Tkinter import *
import tkMessageBox
import tkFileDialog

**Comment by prabindh** [comment]
I believe the below would work for Py3 instead ?

    from tkinter import *
    import messagebox as tkMessageBox
    import filedialog as tkFileDialog

**Comment by dpogosov** [comment]
Yeah, it what I meant.

**Comment by prabindh** [comment]
Done. Please see latest commit.

**Comment by prabindh** [comment]
If this is closed, could you close please ? Thx

**Comment by dpogosov** [comment]
Please use (with 'from tkinter'):
    from tkinter import messagebox as tkMessageBox
    from tkinter import filedialog as tkFileDialog
otherwise doses not work

**Comment by prabindh** [comment]
Finally tried it on Py3 myself, and needed some additional packages as below. Updated code. Please check master (ad84425784b205372b71e2562509fd69199e19c7).

# Python 3
# Python 3 + Pillow on Ubuntu, do the below
# sudo apt-get install python-imaging-tk
# sudo apt-get install python3-pil.imagetk

**Comment by prabindh** [comment]
Thx
