### ISSUE TITLE
Command Execution Problem

### ISSUE THREAD

**Issue by suji104** [prabindh/euclid#8]
When you run
 **$python euclid.py**  

, you will see the following results:

**Traceback (most recent call last):
  File "euclid.py", line 55, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name ImageTk**

What value should I put in ImageTK?
 
Or is the command wrong?
Thank you very much for your reply.

**Comment by prabindh** [comment]
What version of Py is being used ?

**Comment by suji104** [comment]
Thank you for answer.
Python2.7 is in use.

**Comment by prabindh** [comment]
Have you checked this ? http://stackoverflow.com/questions/22788454/importerror-no-module-named-imagingtk/22788542#22788542

**Comment by suji104** [comment]
![image](https://cloud.githubusercontent.com/assets/26781075/24534072/abc095e4-1606-11e7-81f4-d400bee420e2.png)

Did you run this window?
Thank you so much!
Do you have a tutorial on PASCAL to KITTY format?

**Comment by suji104** [comment]
I'm really sorry to keep asking.

**Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "euclid.py", line 165, in loadDir
    self.loadImageAndLabels()
  File "euclid.py", line 325, in loadImageAndLabels
    self.img = Image.open(imagepath)
AttributeError: class Image has no attribute 'open'**

When I select an image folder through Select Dir, I get the following error.
Do you have a solution?

**Comment by prabindh** [comment]
Please pull the latest commit. Looks like an alternative Image module was getting loaded. Thanks !

**Comment by suji104** [comment]
![image](https://cloud.githubusercontent.com/assets/26781075/24534436/f761e582-1608-11e7-9d64-c23c5e7c2d7d.png)

It works properly!
Thank you very much. It has helped a lot.
Have a nice day! :D
