### ISSUE TITLE
Problems saving class labels

### ISSUE THREAD

**Issue by suji104** [prabindh/euclid#9]
Hi, 
I select class 3 and proceed to the next image.
However, it is saved as class 0 continuously.

for bbox in self.bboxList:
 		    if CLASSES[self.classLabelList[labelCnt]] == 'Class0':
			class_txt = 'DontCare'          
       		    elif CLASSES[self.classLabelList[labelCnt]] == 'Class1':
			class_txt = 'Car'
		    elif CLASSES[self.classLabelList[labelCnt]] == 'Class2':
			class_txt = 'Van'
		    elif CLASSES[self.classLabelList[labelCnt]] == 'Class3':
			class_txt = 'Truck'
		    elif CLASSES[self.classLabelList[labelCnt]] == 'Class4':
			class_txt = 'Misc'
                    f.write('%s' %class_txt)               
                    f.write(' 0.0 0 0.0 ')
                    f.write(str(bbox[0])+' '+str(bbox[1])+' '+str(bbox[2])+' '+str(bbox[3]))
                    f.write('%.2f %.2f %.2f %.2f' % (bbox[0], bbox[1], bbox[2], bbo

Can I see why?

Also the coordinates are displayed as x.00 (such as 138.00 239.00 155.00 248.00)
Can not save as a float value?

Thank you for your reply.

**Comment by prabindh** [comment]
what is this code ?

**Comment by suji104** [comment]
Oh no!
I made a stupid mistake.
Solved!
